FROM node:lts-alpine
RUN apk add --update git

ENV USER=avc
ENV UID=12345
ENV GID=23456

RUN adduser \
    --disabled-password \
    "$USER"

USER avc
WORKDIR /home/avc
RUN ls -al 
COPY --chown=avc . .

# RUN git clone https://github.com/levalleux-ludo/AVC-room-booking.git
# CMD cd AVC-room-booking/backend && npm install -y && node ./server.js
CMD npm install -y && npm run start:env-preprod
